### ISSUE TITLE
Wrong "dynamic" encoding on source and target

### ISSUE THREAD

**Issue by ppatierno** [grs/rhea#12]
It seems that dynamic property on source and target is wrongly encoded.
From Wireshark I see 0x00 for false and 0x01 for true and not the right AMQP type boolean encoding 0x42 for false and 0x41 for true.

**Comment by grs** [comment]
A boolean can be encoded in two different ways. Either as a '0 width' value, with distinct typecodes for true (0x41) and false (0x42), or as a 1 byte wide value with 0x56 as the typecode and a value of 0x01 for true and 0x00 for false. Rhea can read and write both encodings. For fields in a compund type it at present uses the 1 byte wide format (that is easy to change).

Was the 0x56 typecode not present in the sequence you saw?

**Comment by ppatierno** [comment]
Just tried ... absolutely ... I can see it in the raw data but the AMQP decoder in Wireshark doesn't support it well. It shows "Dynamic: Unknown (1)" but raw data is 0x56 0x01 so it's ok.
I read the AMQP spec but lost the alternative encoding for boolean values.
