### ISSUE TITLE
did not recognise message section with descriptor 118

### ISSUE THREAD

**Issue by lulf** [grs/rhea#24]
When encoding an AmqpSequence with proton-j and decoding it in rhea, the following log message is displayed:

WARNING: did not recognise message section with descriptor 118

Attached is a junit test that runs a proton-j server passing the desired value to a client opening a receiver. Requires vertx-proton to build.

[unittest.zip](https://github.com/grs/rhea/files/687299/unittest.zip)

**Comment by grs** [comment]
That is fixed in 0.1.8. I've verified your test against the latest and the message gets through as expected (it is exposed as an object with typecode and content fields, in order to distinguish it from a standard amqp value section).
