### ISSUE TITLE
uuid type support for correlation_id property

### ISSUE THREAD

**Issue by pierreca** [grs/rhea#38]
Hi, i'm trying to figure out a way to "force" the library to decode the `correlation_id` property of a message I'm receiving as a UUID. Right now i only get a Buffer (UInt8Array) - i'm trying to make my way through the type system but i get a bit lost in there.... any pointers or suggestions?

Thanks!

[edit] I'm able to "read" the uuid from the buffer by using this package: https://www.npmjs.com/package/uuid-buffer
but I also need to send it "re-encoded" as a uuid - and in that case it looks like I fall into [this "todo" item](https://github.com/grs/rhea/blob/master/lib/types.js#L484)

Feels like either one would need a way to "force" the type of the property OR you'd need to "detect" uuids from strings or buffers and encode them with the proper type (might be expensive). 

thoughts?

**Comment by grs** [comment]
I've checked in a fix, recognising a 16 byte buffer as the message-id.

**Comment by pierreca** [comment]
wow that was quick, thanks :) fix works on my side too, closing!
