### ISSUE TITLE
encoding of message properties of type number

### ISSUE THREAD

**Issue by pierreca** [grs/rhea#39]
I'm sending messages that should have a property that is an http-ish status code (200, 404...)

here's my message object (that I pass "as is" to `sender.send()`):
```js
{
  correlation_id: context.message.correlation_id,
  body: {
    'key': 'value'
  },
  application_properties: {
    'status': 200
  }
}
```

it looks like on the service side the property is either not received, or not received as an Int32 - am i doing anything wrong? is the number type coerced to a smaller integer type? can I force it to Int32?

[edit] typos

**Comment by grs** [comment]
By default it will be sent as a UInt. To send it as an Int, do:

`{
  correlation_id: context.message.correlation_id,
  body: {
    'key': 'value'
  },
  application_properties: {
    'status': rhea.types.wrap_int(200)
  }
}`

**Comment by pierreca** [comment]
brilliant, thanks! is it ok to ask this type of questions here or would you rather use another channel when it's not bugs?

**Comment by grs** [comment]
This is fine.
