### ISSUE TITLE
Extend the test suite

### ISSUE THREAD

**Issue by g0dd4rd** [grs/rhea#5]
I've run "istanbul cover rhea/lib/*js" to get the test coverage of rhea:
=============================== Coverage summary ===============================
Statements   : 29.79% ( 558/1873 )
Branches     : 3.67% ( 27/736 )
Functions    : 3.72% ( 12/323 )
# Lines        : 30.59% ( 558/1824 )

I think it'd be great to increase the coverage.

**Comment by grs** [comment]
Running: istanbul cover _mocha now gives me:

> =============================== Coverage summary ===============================
> Statements   : 89.89% ( 1876/2087 )
> Branches     : 74.75% ( 604/808 )
> Functions    : 88.32% ( 325/368 )
> Lines        : 90.36% ( 1828/2023 )
> ================================================================================

Still plenty more to do, so I'll leave this open. This is just an update on progress.
